version: '3'

services:
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_SMTP_BIND_ADDRESS: 0.0.0.0:1025
      MH_UI_BIND_ADDRESS: 0.0.0.0:8025
      MH_USERS: 'test:test'
